### ISSUE TITLE
Dream nail gauntlet retriggered

### ISSUE THREAD

**Issue by ciplax** [seanpr96/HollowKnight.RandomizerMod#18]
Dream nail gauntlet retriggered when u pass by again even though u've already done it

**Comment by seanpr96** [comment]
This was probably caused by https://github.com/seanpr96/HollowKnight.RandomizerMod/commit/e2f7e8281b15fe2d30f1b298f098cfabf700b988, don't think it happened before. I'll look into it.

**Comment by seanpr96** [comment]
Actually seems likely that fixed the issue, rather than caused it since the bug happened on an old version and I can't reproduce it.
